export const actionTypes = {
  GET_QUESTIONS: 'GET_QUESTIONS',
  GET_QUESTIONS_REQUEST: 'GET_QUESTIONS_REQUEST',
  GET_QUESTIONS_SUCCESS: 'GET_QUESTIONS_SUCCESS',
  GET_QUESTION: 'GET_QUESTION',
  GET_QUESTION_REQUEST: 'GET_QUESTION_REQUEST',
  GET_QUESTION_SUCCESS: 'GET_QUESTION_SUCCESS',
  SUBMIT_ANSWER_SUCCESS: 'SUBMIT_ANSWER_SUCCESS',
  SUBMIT_ANSWER_REQUEST: 'SUBMIT_ANSWER_REQUEST',
  SUBMIT_NEW_QUESTION_REQUEST: 'SUBMIT_NEW_QUESTION_REQUEST',
  SUBMIT_NEW_QUESTION_SUCCESS: 'SUBMIT_NEW_QUESTION_SUCCESS',
  SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  CHECKING_SESSION: 'CHECKING_SESSION',
  RAISE_ERROR: 'RAISE_ERROR'
};
