export const Actions = {
  GET_QUESTIONS: 'GET_QUESTIONS',
  GET_QUESTIONS_REQUEST: 'GET_QUESTIONS_REQUEST',
  GET_QUESTIONS_SUCCESS: 'GET_QUESTIONS_SUCCESS',
  GET_QUESTION: 'GET_QUESTION',
  GET_QUESTION_REQUEST: 'GET_QUESTION_REQUEST',
  GET_QUESTION_SUCCESS: 'GET_QUESTION_SUCCESS',
  SUBMIT_ANSWER_SUCCESS: 'SUBMIT_ANSWER_SUCCESS',
  SUBMIT_ANSWER_REQUEST: 'SUBMIT_ANSWER_REQUEST',
  RAISE_ERROR: 'RAISE_ERROR'
};
